[package]
name = "syshelper"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
clap = "2.34.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.59"